name: Build Windows-Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-windows-release:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install setuptools
    - name: Init submodules
      run: |
        git submodule update --init
    - name: Build script
      run: |
        ./build.bat --release
    - uses: actions/upload-artifact@v4
      with:
        name: mc3ds-tm-windows-x64-urelease-${{ github.sha }}
        path: dist/MC3DS-Texture-Maker/

  build-windows-debug:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install setuptools
    - name: Init submodules
      run: |
        git submodule update --init
    - name: Build script
      run: |
        ./build.bat --debug
    - uses: actions/upload-artifact@v4
      with:
        name: mc3ds-tm-windows-x64-debug-${{ github.sha }}
        path: dist/MC3DS-Texture-Maker/
  
  build-linux-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        sudo apt install dos2unix
        sudo apt install pip
        sudo apt install python3-tk
        pip install -r requirements.txt
        pip install setuptools
    - name: Init submodules
      run: |
        git submodule update --init
    - name: Build script
      run: |
        dos2unix ./build.sh
        chmod +x ./build.sh
        ./build.sh --release
    - uses: actions/upload-artifact@v4
      with:
        name: mc3ds-tm-linux-x64-urelease-${{ github.sha }}
        path: dist/MC3DS-Texture-Maker

  build-linux-debug:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        sudo apt install dos2unix
        sudo apt install pip
        sudo apt install python3-tk
        pip install -r requirements.txt
        pip install setuptools
    - name: Init submodules
      run: |
        git submodule update --init
    - name: Build script
      run: |
        dos2unix ./build.sh
        chmod +x ./build.sh
        ./build.sh --debug
    - uses: actions/upload-artifact@v4
      with:
        name: mc3ds-tm-linux-x64-debug-${{ github.sha }}
        path: dist/MC3DS-Texture-Maker